branch-defaults:
  master:
    environment: null
global:
  application_name: railsplitter2
  default_ec2_keyname: Filezilla
  default_platform: Ruby 2.1 (Passenger Standalone)
  default_region: us-west-2
  profile: eb-cli
  sc: git
